INSTALL_DIR=/usr/local/texlive/texmf-local/tex/latex/local/wits-eie-thesis/

default: install

install:
	mkdir -p $(INSTALL_DIR)
	cp wits-eie-thesis.cls $(INSTALL_DIR)

uninstall:
	rm -rI $(INSTALL_DIR)
